// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Candle struct {
	Symbol              string
	OpenTime            int64
	Open                string
	High                string
	Low                 string
	Close               string
	Volume              string
	CloseTime           int64
	QuoteVolume         string
	Count               int64
	TakerBuyVolume      string
	TakerBuyQuoteVolume string
}
