// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetCandles(ctx context.Context, arg GetCandlesParams) ([]Candle, error)
	GetLatestCandle(ctx context.Context, symbol string) (Candle, error)
	SaveCandle(ctx context.Context, arg SaveCandleParams) error
}

var _ Querier = (*Queries)(nil)
